sudo: false
language: node_js
node_js: '8'
addons:
  sauce_connect: true
matrix:
  fast_finish: true
branches:
  only:
    - master
notifications:
  email:
    on_success: never
cache:
  directories:
  - node_modules

before_script: 'yarn linter'
script: 'yarn test && yarn test:browser'
after_script: 'yarn coverage'
